### PR TITLE
adjust color scale to use it fully

### PR DESCRIPTION
**Pull request by dancek**
I implemented automatic color scale adjustment so that the color scale is fully used every time. This is the default behavior in my version, but you can disable it using the `-G` or `--static-colors` parameters.
## Examples

```
k
```

screen shot 2015-02-20 at 01 45 26

```
k -G
```

screen shot 2015-02-20 at 01 45 54

### CODE REVIEW

**Comment by dancek** [comment]
I think my version is much better for file sizes, as different directories tend to have different file sizes so you rarely get good use of the color scale.

For dates, it's not as good. Dates don't seem to conform to a nice pattern; often you have most files from about the same time, and maybe a couple of newer ones, so often you only get about two colors.

**Comment by supercrabtree** [comment]
Coooool!! This is a way better idea

**Comment by zirrostig** [comment]
I definitely like the file sizes change on this. But I'm not sure about the dates. Could you possible make it so I could use just one or the other maybe something along the lines of
```
-G      --static-colors=WHICH            do not adjust color scale automatically
                                  WHICH=files,dates,both
```
obviously format that to be clearer. zparseopts should be pretty staightforward to do that with.

Otherwise looks great.

**Comment by dancek** [comment]
In these past two months I've forgotten all about the code. I'm also way too busy with our newborn twins. Hopefully someone else can pick this up.

**Comment by zirrostig** [comment]
Most of everything that's wanted is there, I will probably just pick it up
in the next couple days.

Thank you very much for the code as it is, it is something I really wanted
to do or see done.

Also congratulations on the twins!

**Comment by jirutka** [comment]
+1

**Comment by dancek** [comment]
Closing as obsolete.

**Pull request closed without merging**
