### PR TITLE
Suggest a more conventional installation procedure

### PR DESCRIPTION
**Pull request by JoseAlban**

### CODE REVIEW

**Comment by chrstphrknwtn** [comment]
@JoseAlban The language is kind of weird, and also the 'Custom Plugin Download' is specific to oh-my-zsh, in which case the heading seems to make more sense as 'Oh-my-zsh Plug-in'. Also, I think 'Manual Script Download' seems long-winded for no gain, how about just 'Download'?

**Comment by JoseAlban** [comment]
I agree with your points, appreciated feedback.
Not sure if people care about it enough, but at least there's this uncovered installation scenario we could talk about.

**Comment by tomprince** [comment]
I think it makes more sense to suggest using a package manager of some sort first.

**Comment by supercrabtree** [comment]
I included some instructions for installing as a custom plugin, just made it a little clearer that it was for oh-my-zsh. :smile:

**Pull request closed without merging**
