### PR TITLE
Options and Multiple Dirs

### PR DESCRIPTION
**Pull request by zirrostig**
I have been working on adding 'ls' like flags, and making it feel more like a nice 'ls'. This involved adding several command line arguments and making it support multiple directories/files as well. The following is the --help print out.

```
Usage: k [options] DIR
Options:
    -a      --all           list entries starting with .
    -A      --almost-all    list all except . and ..
    -d      --directory     list only directories
    -n      --no-directory  do not list directories
    -h      --human         show filesizes in human-readable format
            --si            with -h, use powers of 1000 not 1024
            --no-vcs        do not get VCS status (much faster)
            --help          show this help
```

I have also fixed serveral small annoyances.
- Symlinks would get a bad warning due to detection of --- --- rwx, #25 
- Relative paths are not displayed on each file when doing something like 'k ../../'
- Many edge cases that were introduced with the addition of command line arguments

And related to open issues
- #28 the slowness is a result of git calls, so using '--no-vcs' makes k almost instant. https://github.com/zirrostig/k/commit/f9d65ca7d125266f3dc286263d49596e9ce5f14f
- #27 obviously working on, and I have plans to add filtering/grouping/sorting based on attributes
- #25 fixed under annoyances. https://github.com/zirrostig/k/commit/cdbfe8088dd39d38b3a1e08d66a1f5d00d744bc3

If you would like me to break this PR into multiple smaller ones I would be more than happy to do so. I just figured I've been sitting on some changes for over 2 months now, it was time to clean up and give back. :)

### CODE REVIEW

**Comment by supercrabtree** [comment]
Awesome!!! Will have a look thorough :)

**Comment by supercrabtree** [comment]
p.s. nice vimrc :+1:

**Comment by supercrabtree** [comment]
Ok, I checked it out and it all looks great, but i get a parse error.

/k/k.sh:318: parse error near `]]'

I don't really have time to look into this do you have any?

Also not getting git status on files, only folders.

Thanks Again :)

**Comment by zirrostig** [comment]
I'll take a look at the problems you mentioned either later today or tomorrow.  

And thanks for the complements, but I have since switched to emacs (with evil of course).

**Comment by supercrabtree** [comment]
ewwww..... emacs. I'm gonna have to reject this pull request now.

just kidding, btw i forgot to mention im using yosemite

**Comment by zirrostig** [comment]
I'm not getting the parse error, so I'm not sure what's causing that. 

Also I have mostly worked out the git status on files issue. Most of it was me forgetting a '$' on a variable name.

What version of zsh are you running? I'm wondering if there is a slight change in zsh that's causing the parse error.

**Comment by supercrabtree** [comment]
zsh 5.0.5 (x86_64-apple-darwin14.0)

**Comment by supercrabtree** [comment]
if i remove
 && ! IS_SYMLINK
its works ok, so it must just be this expression is not valid in the version

**Comment by zirrostig** [comment]
try this
`if [[ $PER3 == "rwx" ]] && (( ! IS_SYMLINK )); then`

**Comment by supercrabtree** [comment]
yup thats working, if you can commit that change I'll merge the request. Thanks again

**Comment by zirrostig** [comment]
Sweet, I still need to finish fixing the git status stuff, then I'll fix the request so you can merge. 

Thanks for testing that.

I'm running zsh 5.0.7 btw. The changelog mentions that they changed globbing behavior in [[ ]] expressions, but that shouldn't have affected the expression here.

**Comment by zirrostig** [comment]
There's that, git really doesn't like being called from outside the working tree.

Everything *should* now work as expected.

**Comment by supercrabtree** [comment]
Great, works perfect. I noticed the --si option didn't give me the warning about numfmt, but i merged it anyway because its an easy fix. Also, what does si stand for?

**Comment by zirrostig** [comment]
--si is a reference to thi SI unit system (International System of Units), more specifically their basis on powers of 10 for numbering, kilo (1000), mega (1mil), etc, whereas in computers, sizes are typically measured using the same kilo,mega,etc, but often refer to powers of 2, kilo being 1024 (2^10), mega is 1048576 (2^20), and so on. --si, makes it use powers of 10 for the size representation, so 1,800,000 bytes would be 1.8M, and without --si would be 1.7M. Its subtle, but some people prefer one or the other. 

Also it's an option in 'ls' so I figured I'd include it.

**Comment by supercrabtree** [comment]
Closes #25

**Pull request merged**
