### PR TITLE
Display unpushed commits

### PR DESCRIPTION
**Pull request by 92bondstreet**
Hi, 

Very nice script !
I added the **unpushed commits** for entire repositories. 

Yassine.

### CODE REVIEW

**Comment by zirrostig** [comment]
Cool feature, after trying the PR out I have found a couple issues.

* I get this error the first time k is ran after getting a fresh shell. 
`k:392: scalar parameter branch created globally in function`
this can be remedied by placing a `typeset branch` somewhere in the code preceding. Its actually line 396 in the file that causes the issue, but its the 392 line of the k function, I don't know why zsh reports it this way.

* You don't prefix the necessary whitespace until encountering a git repo. This can be seen in the following. `.emacs.d` is the first git repo in this particular directory listing, and after it the spacing can be seen.
```
drwxr-xr-x 1 zirro users     168  8 Oct   15:25    .dolphin-emu 
drwx------ 1 zirro users      64  2 Oct   19:16    .elinks 
drwx------ 1 zirro users     296  9 Feb   22:22 |     .emacs.d 
drwxr-xr-x 1 zirro users      46  2 Oct   19:27       .emerald 
```

* Unpushed counts do not update until encountering another git repo. So the files and directories after `.zsh` in the example below have a 1 next to them even though they are not git directories. then `cfg` doesn't have any unpushed commits so it goes away.
```
drwxr-xr-x 1 zirro users      52 28 Oct   15:32       .zkbd 
drwxr-xr-x 1 zirro users     226 13 Feb   00:56 | 1   .zsh 
-rw------- 1 zirro users  238752 13 Feb   00:46   1   .zsh_hist 
lrwxrwxrwx 1 zirro users      11 11 Nov   12:44   1   .zshenv -> .zsh/zshenv
drwxr-xr-x 1 zirro users       8 27 Nov   13:38   1   an 
drwxr-xr-t 2 zirro users      40 12 Feb   17:25   1   atm 
drwxr-xr-x 1 zirro users     354  9 Feb   10:46 |     cfg 
drwxr-xr-x 1 zirro users     536 13 Jan    2014       csm 
```

* It would be preferable to have it calulate the amount of space needed to display the number column and only make it that wide. I understand that this is an extremely nit-picky request, and can probably wait for #31 to be dealt with.

**Comment by 92bondstreet** [comment]
Thanks for you feedback. 
 
I will try to solve point by point your notices !

**Comment by supercrabtree** [comment]
Hi, just for your info the first error: `k:392: scalar parameter branch created globally in function`

Was fixed by this commit: ae05b486f2e30f9e9304b1bea743f66cfd80f329

**Comment by supercrabtree** [comment]
Closing as I can't get this to work myself and with no direction from @92bondstreet

**Pull request closed without merging**
